### ISSUE TITLE
How to use in Docker Compose?

### ISSUE THREAD

**Issue by codeoutin** [djenriquez/sherpa#8]
Hey thanks a lot for sharing this. I did not find out how to use Sherpa in Docker Compose, i'm not sure where the Flag --allow belongs to.
Could someone provide an example? Right now my compose file looks like this:

```
docker-api:
    ports: 
      - "4550:4550"
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
            - 'CONFIG=[ { "Path" : "*", "Access": "allow" } ]'
    image: "djenriquez/sherpa"
```

**Comment by krisnyse** [comment]
bump

**Comment by krisnyse** [comment]
Solved it:
```
  sherpa:
    image: djenriquez/sherpa
    container_name: sherpa
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "4550:4550"
    command: --allow
```
